### ISSUE TITLE
Wrong unicode position for calligraphic characters 𝓠…𝓩

### ISSUE THREAD

**Issue by jorsn** [leftaroundabout/dotfiles#1]
In lines 318–327 of
https://github.com/leftaroundabout/dotfiles/blob/2614c6c323d8c69c9cfefca391f977fd1653cc35/.emacs.d/init.el#L318
, the unicode position should be 1D4D* instead of 1D45* to write calligraphic
characters. U+1D450 is “&#x1D450;”, not “&#x1D4E0;”.

**Comment by leftaroundabout** [comment]
https://github.com/leftaroundabout/dotfiles/commit/10d517f33c8d77a5214d20fc9fbe48deb6a414f4#diff-b664d6253925d6ccf46c39a4b1a2c854R318
